version: '3'
services:
  thesisanalyzer:
    container_name: thesisanalyzer-app
    image: thesisanalyzer:latest
    build: ./ThesisAnalyzer
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    #command: /bin/bash -c gunicorn -w 1 -b 0.0.0.0:8000 ThesisAnalyzer.main:app
  db:
    container_name: thesisanalyzer-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analyzer
    ports:
      - "5432:5432"
    volumes:
      - "./ThesisAnalyzer/setup/db:/docker-entrypoint-initdb.d"
  nginx:
    container_name: thesisanalyzer-nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - thesisanalyzer
    volumes:
      - ./ThesisAnalyzer/static:/usr/src/app/ThesisAnalyzer/static
