# Config file for analysis
from env import LOG_TO_DATABASE

LOG_TO_DATABASE = LOG_TO_DATABASE

ANALYSIS_MAX_CHAR_COUNT = 150000

# Options for analysis
ANALYZE_IMPERSONALITY = True
ANALYZE_OVERUSED_WORDS = True
ANALYZE_SENTENCE_LENGTH = True
ANALYZE_TAGS = True
ANALYZE_OFFICIALESE = True


# Clause analyzer
MAX_CLAUSE_AMOUNT = 4

# Overused word analyzer
OUW_NUM_WORDS_TO_ANALYZE = 8
OVERUSED_MULTIPLIER = 5
MIN_COUNT_OF_LEMMA = 7
MAX_CLUSTER_SIZE = 3
CLUSTER_DISTANCE = 300
