# Config file for style analysis

# Options for analysis
ANALYZE_IMPERSONALITY = True
ANALYZE_OVERUSED_WORDS = True
ANALYZE_SENTENCE_LENGTH = True
ANALYZE_TAGS = True


# Clause analyzer
MAX_CLAUSE_AMOUNT = 4

# Overused word analyzer
OUW_NUM_WORDS_TO_ANALYZE = 8
OVERUSED_MULTIPLIER = 5
MIN_COUNT_OF_LEMMA = 7
MAX_CLUSTER_SIZE = 3
CLUSTER_DISTANCE = 300
